name = "fanctl"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]

executables = ["fanctl"]

[[depends-on]]
pico_bsp = "^2"
